// playground/nuxt/pages/bypass.vue
<template>
	<div class="page">
		<div class="page-content">
			<section class="section">
				<h1>Bypass</h1>
				<p>
					This route is only for the nav link that sets
					<code v-pre>:flyva="false"</code>.
					Navigation is a plain Nuxt link with no Flyva transition.
				</p>
			</section>
		</div>
	</div>
</template>

// playground/next/src/app/bypass/page.tsx
export default function BypassPage() {
	return (
		<div className="page">
			<div className="page-content">
				<section className="section">
					<h1>Bypass</h1>
					<p>
						This route is only for the nav link that sets <code>{'flyva={false}'}</code>.
						Navigation is a plain Next <code>Link</code> with no Flyva transition.
					</p>
				</section>
			</div>
		</div>
	);
}
