// packages/next/runtime/components/flyva-link/FlyvaLink.tsx
'use client';

import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { forwardRef, PropsWithChildren, useImperativeHandle, useMemo, useRef } from 'react';

import type { PageTransitionContext } from '@flyva/shared';

import { useFlyvaTransition } from '../../hooks';
import { useFlyvaLifecycle } from '../../hooks/useFlyvaLifecycle';
import type { FlyvaLinkProps } from './types';

function normalizeUrl(url: string): string {
	try {
		const u = new URL(url, window.location.origin);
		return u.origin + u.pathname.replace(/\/+$/, '');
	} catch {
		return '';
	}
}

function extractPath(input: string): string {
	try {
		const url = new URL(input, window.location.origin);
		return url.pathname;
	} catch {
		return input?.split('?')[0]?.split('#')[0] ?? '';
	}
}

const FlyvaLink = forwardRef<HTMLAnchorElement, PropsWithChildren<FlyvaLinkProps>>((props, ref) => {
	const {
		flyva = true,
		flyvaTransition,
		flyvaOptions,
		onTransitionStart,
		onPrepare,
		onBeforeLeave,
		onLeave,
		onAfterLeave,
		onBeforeEnter,
		onEnter,
		onAfterEnter,
		onCleanup,
		children,
		...linkProps
	} = props;

	const rootEl = useRef<HTMLAnchorElement>(null);
	const transition = useFlyvaTransition();
	const router = useRouter();
	const pathname = usePathname();

	const callbacksRef = useRef({
		onPrepare,
		onBeforeLeave,
		onLeave,
		onAfterLeave,
		onBeforeEnter,
		onEnter,
		onAfterEnter,
		onCleanup,
	});
	callbacksRef.current = {
		onPrepare,
		onBeforeLeave,
		onLeave,
		onAfterLeave,
		onBeforeEnter,
		onEnter,
		onAfterEnter,
		onCleanup,
	};

	const lifecycleCallbacks = useMemo(() => ({
		prepare: (ctx: PageTransitionContext) => { callbacksRef.current.onPrepare?.(ctx); },
		beforeLeave: (ctx: PageTransitionContext) => { callbacksRef.current.onBeforeLeave?.(ctx); },
		leave: (ctx: PageTransitionContext) => { callbacksRef.current.onLeave?.(ctx); },
		afterLeave: (ctx: PageTransitionContext) => { callbacksRef.current.onAfterLeave?.(ctx); },
		beforeEnter: (ctx: PageTransitionContext) => { callbacksRef.current.onBeforeEnter?.(ctx); },
		enter: (ctx: PageTransitionContext) => { callbacksRef.current.onEnter?.(ctx); },
		afterEnter: (ctx: PageTransitionContext) => { callbacksRef.current.onAfterEnter?.(ctx); },
		cleanup: () => { callbacksRef.current.onCleanup?.(); },
	}), []);

	useFlyvaLifecycle(lifecycleCallbacks);

	useImperativeHandle(ref, () => rootEl.current!, []);

	if (!flyva) {
		return (
			<Link ref={rootEl} {...linkProps}>
				{children}
			</Link>
		);
	}

	async function handleClick(e: React.MouseEvent<HTMLAnchorElement, MouseEvent>) {
		const href = rootEl.current?.href ?? props.href?.toString();

		if (!href) return;

		e.preventDefault();

		const currentUrl = window.location.origin + pathname;

		const isCurrent = normalizeUrl(currentUrl) === normalizeUrl(href);
		if (isCurrent) return;

		onTransitionStart?.();

		router.prefetch(href);

		const resolvedOptions = typeof flyvaOptions === 'function' ? flyvaOptions() : flyvaOptions;

		await transition.prepare(flyvaTransition, {
			fromHref: extractPath(currentUrl),
			toHref: extractPath(href),
			...(resolvedOptions ?? {}),
		}, rootEl.current ?? e.target as HTMLElement);

		if (transition.isViewTransition) {
			await transition.leaveWithViewTransition(() => router.push(href));
		} else if (transition.isConcurrent) {
			const deferredLeave = await transition.beginConcurrentLeaveForNavigation();
			router.push(href);
			if (deferredLeave) {
				await transition.completeConcurrentLeaveAfterNavigation();
			}
		} else {
			await transition.leave();
			router.push(href);
		}
	}

	return (
		<Link ref={rootEl} {...linkProps} onClick={handleClick}>
			{children}
		</Link>
	);
});

FlyvaLink.displayName = 'FlyvaLink';

export { FlyvaLink };

// packages/nuxt/runtime/components/flyva-link/FlyvaLink.vue
<script setup lang="ts">
import { NuxtLink } from '#components';
import { navigateTo, useNuxtApp, useRoute, useRuntimeConfig } from '#app';
import { computed, ref } from 'vue';
import { useRouter } from 'vue-router';

import { useFlyvaTransition } from '../../composables';
import { useFlyvaLifecycle } from '../../composables/useFlyvaLifecycle';
import { createDomSwapPromise, setVtActive } from '../../composables/useFlyvaVtState';
import {
	applyViewTransitionNames,
	clearViewTransitionNames,
	supportsViewTransitions,
} from '../../../../shared/view-transition';
import type { FlyvaLinkProps } from './types';

const props = withDefaults(defineProps<FlyvaLinkProps>(), {
	flyva: true,
	prefetch: undefined,
	noPrefetch: undefined,
	custom: undefined,
	external: undefined,
	replace: undefined,
	noRel: undefined,
});

// useFlyvaLifecycle({
// 	beforeLeave: ctx => props.onBeforeLeave?.(ctx),
// 	leave: ctx => props.onLeave?.(ctx),
// 	afterLeave: ctx => props.onAfterLeave?.(ctx),
// 	beforeEnter: ctx => props.onBeforeEnter?.(ctx),
// 	enter: ctx => props.onEnter?.(ctx),
// 	afterEnter: ctx => props.onAfterEnter?.(ctx),
// });

const nuxtLinkBind = computed(() => {
	const {
		flyva: _flyva,
		flyvaTransition: _ft,
		flyvaOptions: _fo,
		onTransitionStart: _ts,
		onPrepare: _op,
		onBeforeLeave: _obl,
		onLeave: _ol,
		onAfterLeave: _oal,
		onBeforeEnter: _obe,
		onEnter: _oe,
		onAfterEnter: _oae,
		onCleanup: _oc,
		...rest
	} = props;
	return rest;
});

const emit = defineEmits<{
	transitionStart: [];
}>();

const rootEl = ref<InstanceType<typeof NuxtLink>>();
const route = useRoute();
const router = useRouter();
const { $flyvaManager } = useNuxtApp();
const { prepare } = useFlyvaTransition();

function resolveFlyvaPath(to: unknown, href: unknown): string {
	const raw = to ?? href;
	if (raw == null || raw === '') return '/';
	if (typeof raw === 'string') {
		if (/^https?:\/\//i.test(raw)) {
			try {
				return new URL(raw).pathname;
			} catch {
				return '/';
			}
		}
		return raw.split('?')[0]?.split('#')[0] ?? '/';
	}
	return router.resolve(raw).path;
}

function normalizeHref(href: string): string {
	return href.replace(/\/+$/, '') || '/';
}

async function onClick() {
	if (!import.meta.client) {
		await navigateTo(props.to ?? props.href);
		return;
	}

	const targetPath = resolveFlyvaPath(props.to, props.href);
	const currentPath = route.path;

	if (normalizeHref(currentPath) === normalizeHref(targetPath)) return;

	emit('transitionStart');
	props.onTransitionStart?.();

	const options = typeof props.flyvaOptions === 'function' ? props.flyvaOptions() : props.flyvaOptions;

	const el = rootEl.value?.$el as Element | undefined;

	await prepare(
		props.flyvaTransition,
		{
			fromHref: currentPath,
			toHref: targetPath,
			...options,
		},
		el,
	);

	const transition = $flyvaManager.runningInstance;
	const config = useRuntimeConfig().public;
	const vtEnabled = config.flyva?.viewTransition && supportsViewTransitions();

	if (vtEnabled && transition) {
		setVtActive(true);
		const context = $flyvaManager.makeContext(el);

		let resolvedNames: Record<string, string> | undefined;
		if (transition.viewTransitionNames) {
			resolvedNames = applyViewTransitionNames(transition.viewTransitionNames, context);
		}

		const domSwap = createDomSwapPromise();

		const vt = document.startViewTransition(async () => {
			await navigateTo(props.to ?? props.href);
			await domSwap;
			if (resolvedNames) {
				applyViewTransitionNames(resolvedNames, context);
			}
		});

		context.viewTransition = vt;

		if (transition.animateViewTransition) {
			await vt.ready;
			await transition.animateViewTransition(vt, context);
		}

		await vt.finished;

		if (resolvedNames) clearViewTransitionNames(resolvedNames);
		transition.cleanup?.();
		$flyvaManager.finishTransition();
		setVtActive(false);
	} else {
		await navigateTo(props.to ?? props.href);
	}
}
</script>

<template>
	<NuxtLink v-if="!flyva" v-bind="nuxtLinkBind"><slot /></NuxtLink>
	<NuxtLink v-else v-bind="nuxtLinkBind" ref="rootEl" @click.prevent="onClick"><slot /></NuxtLink>
</template>
