// packages/next/runtime/hooks/useDetachedRoot.tsx
'use client';

import type { ReactNode, RefObject } from 'react';
import { createRoot, type Root } from 'react-dom/client';

export type RefMap<T extends Record<string, unknown>> = {
	[K in keyof T]: RefObject<T[K]>;
};

export type DetachedRoot<T extends Record<string, unknown>> = {
	refs: RefMap<T>;
	waitForRender: () => Promise<void>;
	destroy: () => void;
};

export function useDetachedRoot<T extends Record<string, unknown>>(
	jsxFactory: (refs: RefMap<T>) => ReactNode,
): DetachedRoot<T> {
	const container = document.createElement('div');
	document.body.appendChild(container);

	const root: Root = createRoot(container);

	const refs = new Proxy({} as Record<string | symbol, { current: unknown }>, {
		get(target, prop: string | symbol) {
			if (!(prop in target)) {
				target[prop] = { current: null };
			}
			return target[prop];
		},
	}) as RefMap<T>;

	root.render(jsxFactory(refs));

	return {
		refs,

		async waitForRender() {
			await new Promise<void>(resolve => {
				requestAnimationFrame(() => resolve());
			});
		},

		destroy() {
			root.unmount();
			container.remove();
		},
	};
}

// packages/nuxt/runtime/composables/useDetachedRoot.tsx
import { createApp, ref, type Ref, type VNode } from 'vue';

export type RefMap<T extends Record<string, unknown>> = {
	[K in keyof T]: Ref<T[K]>;
};

export type DetachedRoot<T extends Record<string, unknown>> = {
	refs: RefMap<T>;
	waitForRender: () => Promise<void>;
	destroy: () => void;
};

type RefBucket<T extends Record<string, unknown>> = Partial<{
	[K in keyof T]: Ref<T[K]>;
}>;

function createRefMap<T extends Record<string, unknown>>(): RefMap<T> {
	const store: RefBucket<T> = {};

	return new Proxy({} as RefMap<T>, {
		get(_target, prop: string | symbol): RefMap<T>[keyof T] {
			if (typeof prop !== 'string') {
				throw new TypeError('DetachedRoot refs use string keys only');
			}
			const key = prop as keyof T;
			let r = store[key];
			if (!r) {
				r = ref(null) as Ref<T[typeof key]>;
				store[key] = r;
			}
			return r;
		},
	});
}

export function useDetachedRoot<T extends Record<string, unknown>>(
	render: (refs: RefMap<T>) => VNode
): DetachedRoot<T> {
	const container = document.createElement('div');
	document.body.appendChild(container);

	const refs = createRefMap<T>();

	const app = createApp({
		setup() {
			return (): VNode => render(refs);
		},
	});

	app.mount(container);

	return {
		refs,

		async waitForRender() {
			await new Promise<void>(resolve => {
				requestAnimationFrame(() => resolve());
			});
		},

		destroy() {
			app.unmount();
			container.remove();
		},
	};
}
